const { C, PAGE, LAYOUT, roleLabel } = require('../tokens');
const { fill, rRect, hRule, drawV } = require('./header');

// ═══════════════════════════════════════════════════════════════
//  COVER PAGE
// ═══════════════════════════════════════════════════════════════
function drawCover(doc, opts) {
  // Dark header band
  fill(doc, 0, 0, PAGE.W, 160, C.ink);
  fill(doc, 0, 160, PAGE.W, 3, C.teal);

  // Logo + brand
  drawV(doc, PAGE.M, 22, 44, C.teal);
  doc.fontSize(LAYOUT.COVER_SIZE).fillColor(C.white).font('Helvetica-Bold')
     .text('VERACITY', PAGE.M + 56, 30);
  doc.fontSize(9).fillColor(C.muted).font('Helvetica')
     .text('AI-Powered Code Risk Analysis', PAGE.M + 56, 56);

  // Role badge — top right
  const rlW = doc.widthOfString(opts.roleLabel, { fontSize: 8 }) + 24;
  rRect(doc, PAGE.W - PAGE.M - rlW, 28, rlW, 22, 3,
    'rgba(255,255,255,0.08)', 'rgba(255,255,255,0.25)', 0.5);
  doc.fontSize(8).fillColor(C.white).font('Helvetica-Bold')
     .text(opts.roleLabel, PAGE.W - PAGE.M - rlW + 12, 35, {
       width: rlW - 24, align: 'center',
     });
  doc.fontSize(7).fillColor(C.muted).font('Helvetica')
     .text(opts.date, PAGE.W - PAGE.M - rlW, 56, {
       width: rlW, align: 'center',
     });

  // Report type + title
  let y = 178;
  doc.fontSize(7).fillColor(C.muted).font('Helvetica')
     .text('REPORT TYPE', PAGE.M, y);
  doc.fontSize(20).fillColor(C.ink).font('Helvetica-Bold')
     .text(opts.title, PAGE.M, y + 10, { width: PAGE.CW });
  y += 38;

  if (opts.subtitle) {
    doc.fontSize(10).fillColor(C.subtle).font('Helvetica')
       .text(opts.subtitle, PAGE.M, y, { width: PAGE.CW });
    y += 16;
  }

  hRule(doc, y, C.rule, 0.5);
  y += 10;

  // Prepared by
  doc.fontSize(7).fillColor(C.muted).font('Helvetica')
     .text('PREPARED BY', PAGE.M, y);
  doc.fontSize(11).fillColor(C.ink).font('Helvetica-Bold')
     .text(opts.name, PAGE.M, y + 10);
  doc.fontSize(8).fillColor(C.subtle).font('Helvetica')
     .text(opts.date, PAGE.M, y + 24);
  y += 36;

  // Summary stat cards
  if (opts.stats && opts.stats.length) {
    hRule(doc, y, C.rule, 0.5);
    y += 10;
    const cw = (PAGE.CW - (opts.stats.length - 1) * 8) / opts.stats.length;
    opts.stats.forEach((s, i) => {
      const cx = PAGE.M + i * (cw + 8);
      rRect(doc, cx, y, cw, 54, 5, C.surface, C.rule, 0.5);
      fill(doc, cx, y, cw, 3, C.teal);
      doc.fontSize(6).fillColor(C.muted).font('Helvetica')
         .text(s.label.toUpperCase(), cx + 10, y + 12, { width: cw - 20 });
      doc.fontSize(18).fillColor(C.ink).font('Helvetica-Bold')
         .text(String(s.value), cx + 10, y + 22, { width: cw - 20 });
    });
    y += 68;
  }

  // ── ABOUT THIS REPORT — fills remaining page space ─────────
  hRule(doc, y, C.rule, 0.5);
  y += 14;

  doc.fontSize(7).fillColor(C.muted).font('Helvetica')
     .text('ABOUT THIS REPORT', PAGE.M, y, { characterSpacing: 0.5 });
  y += 12;

  doc.fontSize(9.5).fillColor(C.body).font('Helvetica')
     .text(
       'This report was generated by the Veracity AI-powered code risk analysis platform. ' +
       'It provides a detailed breakdown of risk indicators, code complexity metrics, SHAP-based ' +
       'feature importance explanations, and actionable mitigation recommendations ' +
       'for the analysed project.',
       PAGE.M, y, { width: PAGE.CW, lineGap: 4 }
     );
  y += 70;

  // Three info tiles
  const tiles = [
    { label: 'Risk Model',     value: 'ML Classifier' },
    { label: 'Explainability', value: 'SHAP Values'   },
    { label: 'Report Format',  value: 'PDF / A4'      },
  ];
  const tw = (PAGE.CW - 16) / 3;
  tiles.forEach((tile, i) => {
    const tx = PAGE.M + i * (tw + 8);
    fill(doc, tx, y, tw, 40, C.tealLight || '#edf7f5');
    fill(doc, tx, y, tw, 3, C.teal);
    doc.fontSize(6.5).fillColor(C.muted).font('Helvetica')
       .text(tile.label.toUpperCase(), tx + 10, y + 8, { width: tw - 20 });
    doc.fontSize(10).fillColor(C.ink).font('Helvetica-Bold')
       .text(tile.value, tx + 10, y + 20, { width: tw - 20 });
  });
  y += 54;

  // Confidentiality notice pinned near bottom
  const noticeY = PAGE.H - 72;
  hRule(doc, noticeY, C.rule, 0.5);
  doc.fontSize(7).fillColor(C.muted).font('Helvetica')
     .text(
       'CONFIDENTIAL — This document is intended solely for the named recipient. ' +
       'Unauthorised distribution or reproduction is strictly prohibited.',
       PAGE.M, noticeY + 10, { width: PAGE.CW, align: 'center' }
     );

  return y;
}

module.exports = { drawCover };